//
//  ProductDetailPresenter.swift
//  product-finder
//
//  Created Isaiin Dev on 16/04/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  The presenter is the only layer that communicates with the view 
//  (The rest of layers communicates with the presenter). Basically, 
//  it’s the layer responsible for making decisions based on the 
//  user’s actions sent by The View.
//
//  This file was generated by the IsaiinDev's iOS Templates so
//  you can apply clean architecture to your iOS projects.
//

import Foundation

protocol ProductDetailPresentationLogic {
    func doSomething(request: ProductDetail.SomeUseCase.Request)
}

class ProductDetailPresenter: Presenter, ProductDetailPresentationLogic {
    // MARK: - Properties

    lazy var view: ProductDetailDisplayLogic = {
        return self._view as! ProductDetailDisplayLogic
    }()

    lazy var interactor: ProductDetailBusinessLogic = {
        return self._interactor as! ProductDetailBusinessLogic
    }()

    lazy var router: ProductDetailRoutingLogic = {
        return self._router as! ProductDetailRoutingLogic
    }()

    // MARK: - PresentationLogic implementation

    func doSomething(request: ProductDetail.SomeUseCase.Request) {
        // Call to interactor
        self.interactor.requestSomething(request: ProductDetail.SomeUseCase.Request())
    }    
}

extension ProductDetailPresenter: ProductDetailBusinessLogicDelegate {
    func presentSuccess(response: ProductDetail.SomeUseCase.Response) {
        self.view.displaySomething(viewModel: ProductDetail.SomeUseCase.ViewModel())
    }

    func presentFailure() {
        self.router.routeToSomewhere()
    }
}
