//
//  ProductDetailWorker.swift
//  product-finder
//
//  Created Isaiin Dev on 16/04/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file is where we will have direct access to our network layer 
//  (APIManager) and our data persistence layer (DataStore), it is important 
//  that all the functions in this class always return something
//
//  This file was generated by the IsaiinDev's iOS Templates so
//  you can apply clean architecture to your iOS projects.
//

import Foundation

class ProductDetailWorker {

}
