//
//  ProductDetailEntity.swift
//  product-finder
//
//  Created Isaiin Dev on 16/04/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Entities are simply our models that the interactor uses through 
//  our repository either for the network layer or data persistence.
//
//  This file was generated by the IsaiinDev's iOS Templates so
//  you can apply clean architecture to your iOS projects.
//

import Foundation

enum ProductDetail {
	// MARK: - Use cases

	enum SomeUseCase {
		struct Request: Codable {}

		struct Response: Codable {}

		struct ViewModel: Codable {}
	}
}