//
//  SimpleCollectionPresenter.swift
//  product-finder
//
//  Created Alejandro isai Acosta Martinez on 12/04/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  The presenter is the only layer that communicates with the view 
//  (The rest of layers communicates with the presenter). Basically, 
//  it’s the layer responsible for making decisions based on the 
//  user’s actions sent by The View.
//
//  This file was generated by the IsaiinDev's iOS Templates so
//  you can apply clean architecture to your iOS projects.
//

import Foundation

protocol SimpleCollectionPresentationLogic {
    func doSomething(request: SimpleCollection.SomeUseCase.Request)
}

class SimpleCollectionPresenter: Presenter, SimpleCollectionPresentationLogic {
    // MARK: - Properties

    lazy var view: SimpleCollectionDisplayLogic = {
        return self._view as! SimpleCollectionDisplayLogic
    }()

    lazy var interactor: SimpleCollectionBusinessLogic = {
        return self._interactor as! SimpleCollectionBusinessLogic
    }()

    lazy var router: SimpleCollectionRoutingLogic = {
        return self._router as! SimpleCollectionRoutingLogic
    }()

    // MARK: - PresentationLogic implementation

    func doSomething(request: SimpleCollection.SomeUseCase.Request) {
        // Call to interactor
        self.interactor.requestSomething(request: SimpleCollection.SomeUseCase.Request())
    }    
}

extension SimpleCollectionPresenter: SimpleCollectionBusinessLogicDelegate {
    func presentSuccess(response: SimpleCollection.SomeUseCase.Response) {
        self.view.displaySomething(viewModel: SimpleCollection.SomeUseCase.ViewModel())
    }

    func presentFailure() {
        self.router.routeToSomewhere()
    }
}
