//
//  SimpleCollectionView.swift
//  product-finder
//
//  Created Alejandro isai Acosta Martinez on 12/04/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This layer contains the UI logic (display, update, animate…) and 
//  responsible for intercepting the user’s action and send it to the 
//  presenter. Most importantly, it has no business logic.
//
//  This file was generated by the IsaiinDev's iOS Templates so
//  you can apply clean architecture to your iOS projects.
//

import UIKit

protocol SimpleCollectionDisplayLogic: View {
	func displaySomething(viewModel: SimpleCollection.SomeUseCase.ViewModel)
}

class SimpleCollectionViewController: UIViewController {
	// MARK: - Properties
	
	lazy var presenter: SimpleCollectionPresentationLogic = {
		return self._presenter as! SimpleCollectionPresentationLogic
	}()

	// MARK: - Object Lifecycle

	override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
		super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
		setup()
	}
  
	required init?(coder aDecoder: NSCoder) {
		super.init(coder: aDecoder)
		setup()
	}	

	// MARK: - View Lifecycle

	override func viewDidLoad() {
		super.viewDidLoad()
		self.setupView()
	}

	// MARK: - Setup

	private func setup() {
		self.setup(
			presenter: SimpleCollectionPresenter(),
			interactor: SimpleCollectionInteractor(),
			router: SimpleCollectionRouter()
		)
	}

	private func setupView() {
        view.backgroundColor = .white
	}

	private func setupConstraints() {
		NSLayoutConstraint.activate([
            // TODO: - Add your views constraints here
        ])
	}

	// MARK: - Actions 
}

extension SimpleCollectionViewController: SimpleCollectionDisplayLogic {
	func displaySomething(viewModel: SimpleCollection.SomeUseCase.ViewModel) {}
}
