//
//  SimpleCollectionRouter.swift
//  product-finder
//
//  Created Alejandro isai Acosta Martinez on 12/04/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This layer is responsible for handling navigation logic: Pushing, 
//  Popping, Presenting UIViewControllers.
//
//  This file was generated by the IsaiinDev's iOS Templates so
//  you can apply clean architecture to your iOS projects.
//

import UIKit

protocol SimpleCollectionRoutingLogic {
  func routeToSomewhere()
}

class SimpleCollectionRouter: Router, SimpleCollectionRoutingLogic {
  lazy var view: SimpleCollectionViewController = {
      return self._view as! SimpleCollectionViewController
  }()

  func routeToSomewhere() {
        
  }
}
